"""Evaluation harness for The Unofficial Guide (Milestone 6).

Runs the 5 test questions from planning.md end-to-end and records, for each:
the question, the retrieved chunks (professor/course/distance), the system's answer,
and the cited sources. Writes a markdown report to eval_results.md.

Accuracy judgments (accurate / partial / inaccurate) are made by a human against the
expected answers in planning.md — this script captures the evidence to judge from.

    python evaluate.py
"""
from __future__ import annotations

from generate import answer

# (question, short expected-answer summary from planning.md)
EVAL_SET = [
    ("I'm choosing a CS61A professor — what do students say about Dan Garcia?",
     "Polarized: praised as an amazing/entertaining lecturer (4.0) BUT criticized for an "
     "unreasonably hard final, refusing to release the distribution, shifting the average "
     "down, and high fail rates (1.0). A correct answer must surface BOTH sides."),
    ("Are John Canny's classes worth taking?",
     "Strongly negative (1.3/5, 20% would take again): 'not prepared for teaching', 'worst "
     "teacher', 'most unclear professor'. Correct = clearly negative + a specific complaint."),
    ("Which CS professor is known for giving good feedback and being patient in office hours?",
     "James O'Brien (CS184): tagged 'Gives good feedback'/'Caring'; 'he'll work with you "
     "until you get it. Very patient.' Tests sparse-signal retrieval (a single relevant chunk)."),
    ("Is CS61B hard, and who's a good professor for it?",
     "CS61B rates difficult (~3-4/5) with two well-liked instructors: Peyrin Kao (4.9/5, "
     "'super easy to follow') and Jonathan Shewchuk ('good style and tempo')."),
    ("Which Berkeley CS / data science professors should I avoid based on reviews?",
     "The negative cluster: John Canny (1.3/5), Zachary Pardos / DATA144 (1.6/5), and "
     "arguably Sarah Chasins / CS164 (2.7/5). Correct = surfaces Canny and Pardos at minimum."),
]


def run() -> str:
    out = ["# Evaluation Results — The Unofficial Guide\n",
           "_Generated by `evaluate.py`. Accuracy judgments added by hand against "
           "planning.md expected answers._\n"]
    for i, (q, expected) in enumerate(EVAL_SET, 1):
        r = answer(q)
        out.append(f"\n## Q{i}. {q}\n")
        out.append(f"**Expected:** {expected}\n")
        out.append(f"**Retrieved (top-{len(r['contexts'])}, cosine distance):**\n")
        for j, c in enumerate(r["contexts"], 1):
            first = c["text"].splitlines()[0]
            out.append(f"{j}. `{c['distance']}` — {c['professor']} ({c['course']}) — {first}")
        out.append(f"\n**System response:**\n\n> {r['answer'].strip()}\n")
        if r["sources"]:
            out.append("**Sources cited:** " + "; ".join(r["sources"]) + "\n")
        out.append("**Accuracy judgment:** _(see Evaluation Report in README.md)_\n")
        out.append("\n---")

    report = "\n".join(out)
    with open("eval_results.md", "w", encoding="utf-8") as f:
        f.write(report)
    return report


if __name__ == "__main__":
    print(run())
    print("\n[written to eval_results.md]")
